name: uotexrd
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - matplotlib
  - tifffile
  - fabio
  - pyfai
  - scikit-image
  - ipykernel
  - jupyterlab
  - pip
